---
detectors:
  Attribute:
    enabled: false
  BooleanParameter:
    enabled: false
  ControlParameter:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  FeatureEnvy:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  IrresponsibleModule:
    enabled: false
  LongParameterList:
    enabled: false
  ManualDispatch:
    enabled: false
  MissingSafeMethod:
    enabled: false
  NestedIterators:
    max_allowed_nesting: 2
  NilCheck:
    enabled: false
  RepeatedConditional:
    enabled: false
  TooManyStatements:
    enabled: false
  UncommunicativeMethodName:
    enabled: false
  UncommunicativeParameterName:
    enabled: false
  UncommunicativeVariableName:
    accept:
      - '/^.$/'
      - '/[0-9]$/'
  UnusedParameters:
    enabled: false
  UtilityFunction:
    enabled: false
