AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5
  Exclude:
    - 'spec/**/**/*'
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
LineLength:
  Max: 100
Metrics/ModuleLength:
  Enabled: false
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/Documentation:
  Enabled: false
